# Generated by Django 6.0 on 2025-12-20 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='route',
            name='polyline',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stops',
        ),
        migrations.AddField(
            model_name='route',
            name='path',
            field=models.JSONField(default=list, help_text='List of stops with lat/lon'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.route'),
        ),
    ]
