# Generated by Django 6.0 on 2025-12-27 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_bus_description_remove_route_polyline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='has_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='issue_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
